FROM python:3.13-slim

WORKDIR /app

COPY requirements-backend.txt .
RUN pip install --no-cache-dir -r requirements-backend.txt

COPY backend/ ./backend/
COPY worker/ ./worker/

CMD ["python", "-m", "worker.worker"]
