apiVersion: apps/v1
kind: Deployment
metadata:
  name: eversports-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eversports-frontend
  template:
    metadata:
      labels:
        app: eversports-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/gerrited/automate-eversports-bookings-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eversports-frontend
spec:
  selector:
    app: eversports-frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eversports-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: bookings.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eversports-frontend
                port:
                  number: 80
